"""add_manager_table

Revision ID: 71e56eec4441
Revises: 72857218e58f
Create Date: 2026-06-16 17:05:22.723825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e56eec4441'
down_revision: Union[str, None] = '72857218e58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_branch_id'), 'managers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_managers_name'), 'managers', ['name'], unique=False)
    op.create_index(op.f('ix_managers_owner_id'), 'managers', ['owner_id'], unique=False)
    op.create_index(op.f('ix_managers_status'), 'managers', ['status'], unique=False)
    op.create_index(op.f('ix_managers_team_id'), 'managers', ['team_id'], unique=False)
    op.create_index(op.f('ix_managers_tenant_id'), 'managers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_tenant_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_team_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_status'), table_name='managers')
    op.drop_index(op.f('ix_managers_owner_id'), table_name='managers')
    op.drop_index(op.f('ix_managers_name'), table_name='managers')
    op.drop_index(op.f('ix_managers_branch_id'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
