"""Add missing columns to Branch

Revision ID: 72857218e58f
Revises: 8b947e519911
Create Date: 2026-06-13 13:58:56.082615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72857218e58f'
down_revision: Union[str, None] = '8b947e519911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('branches', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('branches', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('branches', sa.Column('address', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_column('branches', 'address')
    op.drop_column('branches', 'code')
    op.drop_column('branches', 'city')
    op.drop_column('branches', 'state')
    # ### end Alembic commands ###
