"""initial_schema

Revision ID: 8b947e519911
Revises: 07f2fde4c8d4
Create Date: 2026-06-11 12:07:38.673492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b947e519911'
down_revision: Union[str, None] = '07f2fde4c8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_alerts', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_automation_suggestions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_customer_health', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_daily_briefings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_engine_runs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_executive_summaries', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_insights', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_predictions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_recommendations', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_revenue_leaks', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_risk_scores', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('ai_settings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('assignment_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('branches', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('call_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('calls', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('campaigns', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('communication_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('communication_settings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('communication_templates', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('contacts', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dashboard_widgets', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('deals', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('documents', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_applicants', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_applications', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_approval_rejections', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_bank_selections', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_bank_submissions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_commissions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_documents', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_employments', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_requirements', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('dubai_finance_status_history', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('email_messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('escalation_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('follow_ups', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('integration_connections', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('integration_credentials', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('integration_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('invoice_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('knowledge_base_articles', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('landing_pages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('lead_forms', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('leads', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('meetings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('notes', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('price_books', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('products', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('proposals', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('quote_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('quotes', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('reminder_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('saved_reports', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('segments', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sla_policies', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sms_messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('tasks', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('tax_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('teams', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('tickets', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('webhook_endpoints', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('whatsapp_messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('workflow_runs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('workflows', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('workflow_runs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('whatsapp_messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('webhook_endpoints', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('tickets', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('teams', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('tax_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('tasks', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('sms_messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('sla_policies', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('segments', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('saved_reports', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('reminder_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('quotes', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('quote_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('proposals', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('products', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('price_books', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('notes', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('meetings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('leads', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('lead_forms', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('landing_pages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('knowledge_base_articles', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('invoice_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('integration_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('integration_credentials', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('integration_connections', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('follow_ups', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('escalation_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('email_messages', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_status_history', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_requirements', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_employments', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_documents', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_commissions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_bank_submissions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_bank_selections', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_approval_rejections', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_applications', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dubai_finance_applicants', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('documents', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('deals', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('dashboard_widgets', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('contacts', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('communication_templates', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('communication_settings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('communication_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('campaigns', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('calls', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('call_logs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('branches', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('assignment_rules', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_settings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_risk_scores', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_revenue_leaks', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_recommendations', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_predictions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_insights', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_executive_summaries', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_engine_runs', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_daily_briefings', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_customer_health', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_automation_suggestions', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('ai_alerts', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('accounts', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
