"""add_role_fields

Revision ID: 9e185fbb4f0c
Revises: e20a231d3b3c
Create Date: 2026-06-17 17:35:30.759915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e185fbb4f0c'
down_revision: Union[str, None] = 'e20a231d3b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('data_access_level', sa.String(length=50), nullable=True))
    op.add_column('roles', sa.Column('permissions_matrix', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions_matrix')
    op.drop_column('roles', 'data_access_level')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
