"""add_email_mobile_to_managers

Revision ID: e20a231d3b3c
Revises: 71e56eec4441
Create Date: 2026-06-16 17:25:18.210202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20a231d3b3c'
down_revision: Union[str, None] = '71e56eec4441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('managers', sa.Column('mobile', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_managers_email'), 'managers', ['email'], unique=True)
    op.create_index(op.f('ix_managers_mobile'), 'managers', ['mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_mobile'), table_name='managers')
    op.drop_index(op.f('ix_managers_email'), table_name='managers')
    op.drop_column('managers', 'mobile')
    op.drop_column('managers', 'email')
    # ### end Alembic commands ###
